[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = $PORT

#  Increase upload limit to 2GB
maxUploadSize = 2048

[client]
showSidebarNavigation = true
toolbarMode = "viewer"

[theme]
base = "light"
primaryColor = "#1F7A4F"         # DS Group green
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#000000"
font = "sans serif"
