[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = $PORT

# Max upload size (MB)
# NOTE: Streamlit Cloud HARD LIMIT â‰ˆ 1GB
maxUploadSize = 2048

[client]
showSidebarNavigation = true
toolbarMode = "viewer"

[theme]
base = "light"
primaryColor = "#1F7A4F"          # DS Group Green
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#000000"
font = "sans serif"
